#!/bin/bash
set -e
. ${SCRIPT_DIR}/env-defaults

DIST_SUFFIX='dist'

FILE_VHOST_CONFIG='/etc/apache2/sites-available/self-service-password.conf'
FILE_LSSP_CONFIG='/usr/share/self-service-password/conf/config.inc.local.php'

## Replace placeholders with values
# $1: file with placeholders to replace
# $x: placeholders to replace
update_template() {
  local FILE="${1?missing argument}"
  shift

  [[ ! -f ${FILE} ]] && return 1

  local VARIABLES=($@)
  local USR=$(stat -c %U "${FILE}")
  local tmp_file="$(mktemp)"
  cp -a "${FILE}" "${tmp_file}"

  local variable
  for variable in ${VARIABLES[@]}; do
    # Keep the compatibilty: {{VAR}} => ${VAR}
    sed -ri "s/[{]{2}$variable[}]{2}/\${$variable}/g" "${tmp_file}"
  done

  # Replace placeholders
  (
    export ${VARIABLES[@]}
    local IFS=":"; sudo -HEu ${USR} envsubst "${VARIABLES[*]/#/$}" < "${tmp_file}" > "${FILE}"
  )
  rm -f ${tmp_file}
}

finalize_parameters() {
  # is a ldap and/or mail server linked?
  if [[ -n ${LDAP_PORT_389_TCP_ADDR} ]]; then
    # Used, when the Docker legacy container link is used (Docker-Compose V1)
    echo "Auto-Conf LSSP"

    dc_string=""
    IFS="."; declare -a dc_parts=($LDAP_ENV_SLAPD_DOMAIN)
    for dc_part in "${dc_parts[@]}"; do
      dc_string="$dc_string,dc=$dc_part"
    done
    dc_string=${dc_string:1}

    LDAP_BASE="${dc_string}"
    LDAP_URL=ldap://${LDAP_PORT_389_TCP_ADDR}:${LDAP_PORT_389_TCP_PORT}

    # support for linked sameersbn/mysql image
    # Edit: Commented this line because override LDAP_USER variable at any time. This was relocated to env-default.
    # LDAP_USER="cn=admin,${LDAP_BASE}"
    LDAP_PASS=${LDAP_ENV_SLAPD_PASSWORD}
  else
    # Used, when no container is linked, or Docker-Compose V2 is used!
    echo "Pre-Conf LSSP"
   
    if [[ -n ${SLAPD_DOMAIN} && -n ${SLAPD_PASSWORD} ]]; then
      echo "Use SLAPD-variables ..."
      LDAP_DOMAIN=${SLAPD_DOMAIN}
      LDAP_PASS=${SLAPD_PASSWORD}
    fi

    dc_string=""
    IFS="."; declare -a dc_parts=($LDAP_DOMAIN)
    for dc_part in "${dc_parts[@]}"; do
      dc_string="$dc_string,dc=$dc_part"
    done
    dc_string=${dc_string:1}

    LDAP_BASE="${LDAP_BASE:-${dc_string}}"

    # support for linked sameersbn/mysql image
    # Edit: Commented this line because override LDAP_USER variable at any time. This was relocated to env-default.
    # LDAP_USER="cn=admin,${LDAP_BASE}"
  fi

  if [[ -z ${LDAP_URL} ]]; then
    echo
    echo "ERROR: "
    echo "  Please configure the LDAP connection."
    echo "  Cannot continue without a LDAP server. Aborting..."
    echo
    echo "Current Environment:"
    env
    return 1
  fi

  if [[ -n ${MAIL_PORT_25_TCP_ADDR} ]]; then
    echo "Auto-Conf MAIL-Host"

    SMTP_HOST=${MAIL_PORT_25_TCP_ADDR}
    SMTP_PORT=${MAIL_PORT_25_TCP_PORT}
  fi

  if [[ -n ${SMTP_HOST} && -n ${SMTP_PORT} ]]; then
    echo "Enable MAIL"
    LSSP_MAIL_SUPPORT=true

    LSSP_KEYPHRASE=${LDAP_KEYPHRASE:-}
    if [ -z "${LSSP_KEYPHRASE}"]; then
      LSSP_KEYPHRASE=$(pwgen -1 32)
      echo "  ... generated temporary keyphrase"
    fi

    # Enable Authentication, if Username and Password are provided
    if [[ -n ${SMTP_USER} && -n ${SMTP_PASS} ]]; then
      echo "  ... with AUTH"
      SMTP_USEAUTH=true
    else
      echo "  ... without AUTH"
      SMTP_USEAUTH=false
    fi
  else
    echo "Disable MAIL"
    LSSP_MAIL_SUPPORT=false
  fi

  VIRTUAL_SUBDIR=${VIRTUAL_SUBDIR:-lssp}
}

configure_lssp() {
  echo "Configuring LSSP"

  cp -v "${FILE_LSSP_CONFIG}.${DIST_SUFFIX}" "${FILE_LSSP_CONFIG}"

  update_template "${FILE_LSSP_CONFIG}" \
    LDAP_URL \
    LDAP_USER \
    LDAP_PASS \
    LDAP_BASE \
    LDAP_AD_MODE \
    LDAP_STARTTLS \
    LSSP_ATTR_LOGIN LSSP_ATTR_FN LSSP_ATTR_MAIL \
    LSSP_HASH_METHOD \
    LSSP_KEYPHRASE \
    LSSP_MAIL_FROM_LDAP \
    LSSP_SHOW_MENU \
    SMTP_USEAUTH \
    SMTP_FROM \
    SMTP_HOST \
    SMTP_PORT \
    SMTP_USER \
    SMTP_PASS \
    SMTP_TLS \
    SMTP_DOMAIN \
    LSSP_MAIL_SUPPORT \
    LSSP_DEFAULT_ACTION \
    RECAPTCHA_USE \
    RECAPTCHA_PUB_KEY \
    RECAPTCHA_PRV_KEY \
    RECAPTCHA_THEME \
    RECAPTCHA_SSL

  update_template "${FILE_VHOST_CONFIG}" \
    VIRTUAL_SUBDIR
}

